CREATE TABLE IF NOT EXISTS jobs (
	id uuid PRIMARY KEY DEFAULT uuidv4(),
	code TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
