CREATE TABLE IF NOT EXISTS volumes (
	id uuid PRIMARY KEY DEFAULT uuidv4(),
	name VARCHAR(255) NOT NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
