basePath: /
definitions:
  tool.GetToolResponse:
    properties:
      name:
        type: string
      spec:
        $ref: '#/definitions/tsf.Tool'
    type: object
  tsf.EnvVar:
    properties:
      name:
        type: string
    type: object
  tsf.Executable:
    properties:
      command:
        type: string
      modifiers:
        additionalProperties:
          $ref: '#/definitions/tsf.Modifier'
        type: object
      stdin:
        type: boolean
    type: object
  tsf.IOType:
    enum:
    - 0
    - 0
    - 0
    - 0
    type: integer
    x-enum-varnames:
    - FILE
    - STRING
    - STDOUT
    - STDIN
  tsf.IOVariable:
    properties:
      name:
        type: string
      type:
        $ref: '#/definitions/tsf.IOType'
    type: object
  tsf.Modifier:
    properties:
      string:
        type: string
      variables:
        items:
          type: string
        type: array
    type: object
  tsf.Tool:
    properties:
      env:
        items:
          $ref: '#/definitions/tsf.EnvVar'
        type: array
      exe:
        $ref: '#/definitions/tsf.Executable'
      inputs:
        items:
          $ref: '#/definitions/tsf.IOVariable'
        type: array
      name:
        type: string
      outputs:
        items:
          $ref: '#/definitions/tsf.IOVariable'
        type: array
      sandbox:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: WorkerEngine is a sandbox API to execute TSF based software.
  title: WorkerEngine API
  version: "1.0"
paths:
  /tool/:
    get:
      consumes:
      - application/json
      description: Get the name of all available tools
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
      summary: Get all available tools
      tags:
      - tools
  /tool/{name}:
    get:
      consumes:
      - application/json
      description: Get details for a tool
      parameters:
      - description: Tool name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.GetToolResponse'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get available tool by name
      tags:
      - tools
swagger: "2.0"
